// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ToddsAPI.Models
{
    public partial class Sample
    {
        public int Id { get; set; }
        public string TextStr { get; set; }
    }
}